//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASCOM.SQMLite.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASCOM.SQMLite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SQMLite.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ASCOM {
            get {
                object obj = ResourceManager.GetObject("ASCOM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Characteristic {0} found.
        /// </summary>
        internal static string CaractéristiqueXTrouvee {
            get {
                return ResourceManager.GetString("CaractéristiqueXTrouvee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection....
        /// </summary>
        internal static string Connexion {
            get {
                return ResourceManager.GetString("Connexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection to device {0} successfully established.
        /// </summary>
        internal static string ConnexionAuPeripheriqueEffectueeAvecSucces {
            get {
                return ResourceManager.GetString("ConnexionAuPeripheriqueEffectueeAvecSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disconnect....
        /// </summary>
        internal static string Deconnexion {
            get {
                return ResourceManager.GetString("Deconnexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Device {0} successfully disconnected.
        /// </summary>
        internal static string DeconnexionDuPeripheriqueEffectueeAvecSucces {
            get {
                return ResourceManager.GetString("DeconnexionDuPeripheriqueEffectueeAvecSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        /// </summary>
        internal static System.Drawing.Icon DefaultIcon {
            get {
                object obj = ResourceManager.GetObject("DefaultIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Starting initialisation.
        /// </summary>
        internal static string DemarageDeLInitialisation {
            get {
                return ResourceManager.GetString("DemarageDeLInitialisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ASCOM Driver for SQMLite.
        /// </summary>
        internal static string DriverASCOMPourModuleSQMLite {
            get {
                return ResourceManager.GetString("DriverASCOMPourModuleSQMLite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Characteristic reading error {0}: {1}.
        /// </summary>
        internal static string ErreurLectureCaracteristiqueXY {
            get {
                return ResourceManager.GetString("ErreurLectureCaracteristiqueXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occured while sending command.
        /// </summary>
        internal static string ErreurLorsDeLEnvoiDeLaCommande {
            get {
                return ResourceManager.GetString("ErreurLorsDeLEnvoiDeLaCommande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : {0}.
        /// </summary>
        internal static string ErreurX {
            get {
                return ResourceManager.GetString("ErreurX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Github of the SQMLite project.
        /// </summary>
        internal static string GithubDuSQMLite {
            get {
                return ResourceManager.GetString("GithubDuSQMLite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to connect to the BLE device.
        /// </summary>
        internal static string ImpossibleDeSeConnecterAuPeripheriqueBLE {
            get {
                return ResourceManager.GetString("ImpossibleDeSeConnecterAuPeripheriqueBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initialisation done succesfully.
        /// </summary>
        internal static string InitialisationEffectueeAvecSucces {
            get {
                return ResourceManager.GetString("InitialisationEffectueeAvecSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Juanito del Pepito.
        /// </summary>
        internal static string JuanitoDelPepito {
            get {
                return ResourceManager.GetString("JuanitoDelPepito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Characteristic {0}, value = {1}.
        /// </summary>
        internal static string LectureCaracteristiqueXValeurY {
            get {
                return ResourceManager.GetString("LectureCaracteristiqueXValeurY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reading the value of the characteristic {0}.
        /// </summary>
        internal static string LectureDeLaValeurDeLaCaracteristiqueX {
            get {
                return ResourceManager.GetString("LectureDeLaValeurDeLaCaracteristiqueX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sky brightness.
        /// </summary>
        internal static string LuminositeDuCiel {
            get {
                return ResourceManager.GetString("LuminositeDuCiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trace log enable.
        /// </summary>
        internal static string ModeTraceActive {
            get {
                return ResourceManager.GetString("ModeTraceActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SQMLite module already connected.
        /// </summary>
        internal static string ModuleSQMLiteDejaConnecte {
            get {
                return ResourceManager.GetString("ModuleSQMLiteDejaConnecte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SQMLite device settings.
        /// </summary>
        internal static string ParametresDuPeripheriqueSQMLite {
            get {
                return ResourceManager.GetString("ParametresDuPeripheriqueSQMLite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No custom actions supported. Empty list returned..
        /// </summary>
        internal static string PasDeCustomActionsSupporteesRenvoiDUneListeVide {
            get {
                return ResourceManager.GetString("PasDeCustomActionsSupporteesRenvoiDUneListeVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No SQMLite module detected.
        /// </summary>
        internal static string PasDeModuleSQMLiteDetecte {
            get {
                return ResourceManager.GetString("PasDeModuleSQMLiteDetecte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No serial port defined.
        /// </summary>
        internal static string PasDePortSerieDefiniDansLesParametres {
            get {
                return ResourceManager.GetString("PasDePortSerieDefiniDansLesParametres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dew point.
        /// </summary>
        internal static string PointDeRosee {
            get {
                return ResourceManager.GetString("PointDeRosee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Detected BLE Devices list.
        /// </summary>
        internal static string PortSerie {
            get {
                return ResourceManager.GetString("PortSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Atmospheric pressure.
        /// </summary>
        internal static string PressionAtmospherique {
            get {
                return ResourceManager.GetString("PressionAtmospherique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sky quality.
        /// </summary>
        internal static string QualiteDuCiel {
            get {
                return ResourceManager.GetString("QualiteDuCiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SQMLite {
            get {
                object obj = ResourceManager.GetObject("SQMLite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SQMLite BLE Device found. Attempting to connect....
        /// </summary>
        internal static string SQMLiteBLEDeviceTrouveTentativeDeConnexion {
            get {
                return ResourceManager.GetString("SQMLiteBLEDeviceTrouveTentativeDeConnexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SQMLite BLE Service found.
        /// </summary>
        internal static string SQMLiteBLEServiceTrouve {
            get {
                return ResourceManager.GetString("SQMLiteBLEServiceTrouve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Humidity rate.
        /// </summary>
        internal static string TauxDHumidite {
            get {
                return ResourceManager.GetString("TauxDHumidite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ambient temperature.
        /// </summary>
        internal static string TemperatureAmbiante {
            get {
                return ResourceManager.GetString("TemperatureAmbiante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Timeout: BLE connection failed after 15 seconds.
        /// </summary>
        internal static string TimeoutConnexionBLEImpossibleApres15Secondes {
            get {
                return ResourceManager.GetString("TimeoutConnexionBLEImpossibleApres15Secondes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Value : {0} - Read in {1} ms.
        /// </summary>
        internal static string ValeurXLectureEnYMs {
            get {
                return ResourceManager.GetString("ValeurXLectureEnYMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please disconnect SQMLite module to access settings.
        /// </summary>
        internal static string VeuillezDeconnecterLeModuleSQMLitePourAccederAuxParametres {
            get {
                return ResourceManager.GetString("VeuillezDeconnecterLeModuleSQMLitePourAccederAuxParametres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have not paired any devices.
        /// </summary>
        internal static string VousNAvezAppaireAucunPeripherique {
            get {
                return ResourceManager.GetString("VousNAvezAppaireAucunPeripherique", resourceCulture);
            }
        }
    }
}
